set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	
set_property PACKAGE_PIN W7 [get_ports {cathode[7]}]					
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[7]}]
    set_property PACKAGE_PIN W6 [get_ports {cathode[6]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
    set_property PACKAGE_PIN U8 [get_ports {cathode[5]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
    set_property PACKAGE_PIN V8 [get_ports {cathode[4]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
    set_property PACKAGE_PIN U5 [get_ports {cathode[3]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
    set_property PACKAGE_PIN V5 [get_ports {cathode[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
    set_property PACKAGE_PIN U7 [get_ports {cathode[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
    
    set_property PACKAGE_PIN V7 [get_ports {cathode[0]}]                            
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
    
    set_property PACKAGE_PIN U2 [get_ports {anode[0]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {anode}]
    set_property PACKAGE_PIN U4 [get_ports {anode[1]}]                    
        #set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
    set_property PACKAGE_PIN V4 [get_ports {anode[2]}]                    
        #set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
    set_property PACKAGE_PIN W4 [get_ports {anode[3]}]                    
        #set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property PACKAGE_PIN W19 [get_ports next]						
       set_property IOSTANDARD LVCMOS33 [get_ports next]
set_property PACKAGE_PIN T17 [get_ports rst]                        
       set_property IOSTANDARD LVCMOS33 [get_ports rst]
            
set_property PACKAGE_PIN V17 [get_ports {num[0]}]					
  set_property IOSTANDARD LVCMOS33 [get_ports {num}]
set_property PACKAGE_PIN V16 [get_ports {num[1]}]                    
          # set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {num[2]}]                    
           #set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {num[3]}]                    
           #set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]

set_property PACKAGE_PIN W15 [get_ports {init[0]}]         
  set_property IOSTANDARD LVCMOS33 [get_ports {init}]
set_property PACKAGE_PIN V15 [get_ports {init[1]}]         
#  set_property IOSTANDARD LVCMOS33 [get_ports {init[2]}]
set_property PACKAGE_PIN W14 [get_ports {init[2]}]         
#  set_property IOSTANDARD LVCMOS33 [get_ports {init[3]}]
set_property PACKAGE_PIN W13 [get_ports {init[3]}]         
#  set_property IOSTANDARD LVCMOS33 [get_ports {init[4]}]
set_property PACKAGE_PIN V2 [get_ports {init[4]}]          
#  set_property IOSTANDARD LVCMOS33 [get_ports {init[5]}]
set_property PACKAGE_PIN T3 [get_ports {init[5]}]          
#  set_property IOSTANDARD LVCMOS33 [get_ports {init[6]}]

set_property PACKAGE_PIN T2 [get_ports {mask[0]}]         
  set_property IOSTANDARD LVCMOS33 [get_ports {mask}]
set_property PACKAGE_PIN R3 [get_ports {mask[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {mask[2]}]         
#  set_property IOSTANDARD LVCMOS33 [get_ports {mask}]
set_property PACKAGE_PIN U1 [get_ports {mask[3]}]         
  #set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {mask[4]}]         
  #set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {mask[5]}]         
  # set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]